name: Update GitHub Stats Cards

on:
  schedule:
    - cron: '0 0 * * *' # every monday
  workflow_dispatch: {}   # supaya bisa dipicu manual dari tab "Actions"

permissions:
  contents: write   # supaya job ini boleh push commit balik ke repo

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Generate stats cards
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}
        run: cargo run --release

      - name: Commit & push perubahan
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub stats cards"
          file_pattern: ".github/*.svg .github/loc_cache/*.json"
